version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:${DB_VERSION:-10.11.2}'
    container_name: rep_database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-main}
    ports:
      - '3306'
###< doctrine/doctrine-bundle ###

  dbadmin:
    image: 'phpmyadmin:latest'
    container_name: rep_dbadmin
    environment:
      PMA_HOST: database
    depends_on:
      - database
    ports:
      - 8100:80

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###